# Generated by Django 5.0.4 on 2024-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrek_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='movie',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(max_length=255),
        ),
    ]
